spring:
  application:
    name: railway-network
  cache:
    type: redis
  data:
    redis:
      host: localhost
      port: 6379   

openrouteservice:
  api:
    key: 5b3ce3597851110001cf6248fd94ee1949734381a341d8e084fd4857

  
